name = "żuż"
author = "def750"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a5c8798897cc9c9be578ed05526c9ff5849136ab40bd482a89584b1aa645448"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
