name = "żuż"
author = "def750"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9006f4fe167b13d420a7f876d815c6aafbfdb664b7a894c3cf3d50d64aee3085"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
