name = "żuż"
author = "def750"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dba7fd71d9f1249dd45b0b63f64c44fea8a15cea5d9d0eb55a8e77650f33f27c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
